#version: '2'
services:
  web:
    build: .
    depends_on:
        - db
    ports:
      - '8000:8000'
    volumes:
      - .:/home/app
      - /home/app/node_modules
  db:
    image: mongo:5.0.5
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

volumes:
    mongodata: